but when it does run_tests again, it going to create another domain and another timeout