happyGilmorian: from looking at other examples it seems I should pass an error catching function in as the callback. Seems to work.