i could throw an exception and catch it but is there a better way?