in fact, it wouldn't be possible to exception handle a core fs.* method, so error handling relies on the err passed back