since node core is supposed to call your callback with an error as the first arg.