mher_: also it might just be a limitation of the protocol you're using but its a little weird that there is 1 top level error handler as opposed to the error getting returned into the .call callback as the first argument