Well if you return from the fail then you are handling it