this has happened before, I guess python does not like having reasonable or predictable version numbers