and of course, .fail can rethrow the error, if it can't handle it.