is there a way to 'catch' an error in a domain.on('error') event so process doesn't emit 'uncaughtException'?