Can I do a 'break on exception' somehow?