gerconfused, whenever you use an async, callback-style function inside your own function, you also need to make your function use callback style. the custom is to make it the last parameter to your function the callback, and to call that callback with the first parameter being the error, and the second (and possibly more) being the return value(s)