bnoordhuis: so sometimes res.on('end') will fire _and_ req.on('error') will fire?