with promises its always handled directly by the .then() method and it passes it down the chain until a handleError method is defined. if u chain one to the end of your .then-chain, then its effectively like a domain