suppose you are writing code that sould run after you saved something to a db - your callback will be called in a callstack of the db driver of some third party - like mongoose... they might try to cacth all of their exceptions - which will also catch yours.